project:
  name: babymoment

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  servlet:
    # size limit
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  # mysql config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  # jpa
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    # Processing false because connections become scarce when there is heavy traffic
    open-in-view: false
  data:
    # redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  shutdown: graceful
  port: ${SERVER_PORT_1}

# token
token:
  secret: ${TOKEN_SECRET}
  # time to live
  ttl:
    access-token: 3600000 # 3600 seconds(1 hour)
    refresh-token: 864000000 # 864000 seconds(10 days)

# upload
upload:
  path:
    baby:
      image: /var/www/babymoment/upload/baby/image/

# swagger config
springdoc:
  packages-to-scan: com.benection.babymoment.api.controller
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    path: /api-docs
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

apple:
  bundle-id: ${APPLE_BUNDLE_ID}

---
spring:
  config:
    activate:
      on-profile: local-profile

server:
  port: ${SERVER_PORT_1}

# token
token:
  # time to live
  ttl:
    access-token: 10000 # 10 seconds

---
spring:
  config:
    activate:
      on-profile: prod-profile-1

server:
  port: ${SERVER_PORT_1}

---
spring:
  config:
    activate:
      on-profile: prod-profile-2

server:
  port: ${SERVER_PORT_2}
